import type { Metadata } from "next";
import {  Roboto } from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";
import Navigations from './../stories/navigation/Navigations'
import NavFooter from "@/stories/navigation/NavFooter";
const roboto = Roboto({ weight: ["100","300","500","700"] , subsets: ['latin']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html  className='dark ? ' lang="en">
      <body  className={roboto.className}>
      <Providers>
        <Navigations />
          {children}
          <NavFooter />
        </Providers></body>
    </html>
  );
}
